// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr1CIbzqt4VBSnGvMjtw_zpt5ClUDbJYc',
    appId: '1:823219855369:ios:a6ea8f1a463687bce698d8',
    messagingSenderId: '823219855369',
    projectId: 'resty-f62d5',
    storageBucket: 'resty-f62d5.firebasestorage.app',
    iosClientId: '823219855369-vg1gp86kljn6gtb6k6srlcpt2ujrh8kf.apps.googleusercontent.com',
    iosBundleId: 'ru.http.collector.postmanovich',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQr5aEKgm0d6BDJTQN0jBvgSQhzFcciik',
    appId: '1:823219855369:web:e3ee6f8152165434e698d8',
    messagingSenderId: '823219855369',
    projectId: 'resty-f62d5',
    authDomain: 'resty-f62d5.firebaseapp.com',
    storageBucket: 'resty-f62d5.firebasestorage.app',
    measurementId: 'G-SGYWJ5E73E',
  );

}